function Hd = v3lp(FreqPass, Fs, Width, dbDrop)
%V3LP Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.4 and the Signal Processing Toolbox 6.7.
%
% Generated on: 21-Jun-2007 11:16:15
%

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
%Fs = 24414;  % Sampling Frequency

Fpass = FreqPass;                % Passband Frequency
Fstop = FreqPass + Width;              % Stopband Frequency
Dpass = 0.057501127785;   % Passband Ripple
Dstop = 0.0056234132519 / (10^((dbDrop - 45)/20));  % Stopband Attenuation
dens  = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);
Hd.Numerator = Hd.Numerator ./ sum(Hd.Numerator);

% [EOF]
