function Hd = v3strong(FreqIn, Fs, Width, dbDrop, FreqPass2)
%V3STRONG Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.4 and the Signal Processing Toolbox 6.7.
%
% Generated on: 20-Jun-2007 12:50:15
%

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
%Fs = 24414;  % Sampling Frequency

if(~exist('FreqPass2','var'))
    FreqPass2 = FreqIn;
end

Fstop1 = FreqIn - Width;             % First Stopband Frequency
Fpass1 = FreqIn;             % First Passband Frequency
Fpass2 = FreqPass2 + 1;             % Second Passband Frequency
Fstop2 = FreqPass2 + Width + 1;             % Second Stopband Frequency
Dstop1 = (0.0056234132519) / (10^((dbDrop - 45)/20));  % First Stopband Attenuation
Dpass  = 0.057501127785;   % Passband Ripple
Dstop2 = (0.0056234132519) / (10^((dbDrop - 45)/20));  % Second Stopband Attenuation
dens   = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
