function acqgui_overnightBatch(expers)
% expers is a cell array of exper structures

for ii = 1:length(expers)
    birdname = expers{ii}.birdname;
    expername = expers{ii}.expername;
    switch birdname
        case '2036'
            annotate_exper('2036', expername, ...
                'edgeSyllThreshold', -11, ...
                'triggerSyllThreshold', -8)
            fprintf(1, 'Annotated exper %s for bird %s\n', expername, birdname)
        case '2055'
            annotate_exper('2055', expername, ...
                'edgeSyllThreshold', -10.5, ...
                'triggerSyllThreshold',-6 , ...
                'fMinIntervalDuration', 0.025)
            fprintf(1, 'Annotated exper %s for bird %s\n', expername, birdname)
        case 'mes003'
            annotate_exper('mes003', expername, ...
                'edgeSyllThreshold', -11, ...
                'triggerSyllThreshold', -8)
            fprintf(1, 'Annotated exper %s for bird %s\n', expername, birdname)
        case '2089'
            annotate_exper('2089', expername, ...
                'edgeSyllThreshold', -11, ...
                'triggerSyllThreshold', -7, ...
                'fMinIntervalDuration', 0.02)
            fprintf(1, 'Annotated exper %s for bird %s\n', expername, birdname)
        otherwise
            fprintf(1, 'Skipping exper %s for bird %s\n', expername, birdname)
    end
end