function acqgui_overnightBatch(expers)
% expers is a cell array of exper structures

for ii = 1:length(expers)
    birdname = expers{ii}.birdname;
    expername = expers{ii}.expername;
    switch birdname
        case '2098'
            annotate_exper('2098', expername, ...
                'edgeSyllThreshold', -8, ...
                'triggerSyllThreshold', -6, ...
                'fMinIntervalDuration',0.03)
            fprintf(1, 'Annotated exper %s for bird %s\n', expername, birdname)
        case 'mes005'
            annotate_exper('mes005', expername, ...
                'edgeSyllThreshold', -11, ...
                'triggerSyllThreshold', -7, ...
                'fMinIntervalDuration', 0.02)
            fprintf(1, 'Annotated exper %s for bird %s\n', expername, birdname)
        case 'mes003'
            annotate_exper('mes003', expername, ...
                'edgeSyllThreshold', -11, ...
                'triggerSyllThreshold', -8)
            fprintf(1, 'Annotated exper %s for bird %s\n', expername, birdname)
        case '2089'
            annotate_exper('2089', expername, ...
                'edgeSyllThreshold', -11, ...
                'triggerSyllThreshold', -7, ...
                'fMinIntervalDuration', 0.02)
            fprintf(1, 'Annotated exper %s for bird %s\n', expername, birdname)
        otherwise
            fprintf(1, 'Skipping exper %s for bird %s\n', expername, birdname)
    end
end